### ISSUE TITLE
Cannot set default EP status

### ISSUE THREAD

**Issue by IskanderNovena** [SiCKRAGETV/sickrage-issues#111]
When I edit an existing show and set the default episode status to something other than Wanted (the default) and click Save changes, the change isn't reflected on the episode-page. Default EP Status is blank in the info-box.
When editing the settings again, the default episode status is (again/still) set to Wanted.

Running BRANCH: (master) / COMMIT: (1b850b3aaa7e62c325230b30517f16ca3350d52b) 
Python: 2.7.8 (default, Sep 10 2014, 01:03:16) [GCC 4.3.2]
Running on a Synology DS213+.

**Comment by abeloin** [comment]
@IskanderNovena Try this pull request SiCKRAGETV/SickRage#1197 it should be working again.

**Comment by abeloin** [comment]
@fernandog Can you close this issue? Thank You

**Comment by IskanderNovena** [comment]
Not sure how I should pull the request, since I'm not familiar with Git. Also, I run SickRage on a Synology. For now, the issue still persists with this version: BRANCH: (master) / COMMIT: (401cb666016e45b42fe675bafdf7908ad6c2b9bb)

**Comment by abeloin** [comment]
@IskanderNovena Did it work?

**Comment by IskanderNovena** [comment]
Seems to be working; the GUI shows the setting correctly. I can tell if it actually works this weekend, when one show I follow and have set to ignore will air a new episode.

**Comment by abeloin** [comment]
Ok

**Comment by IskanderNovena** [comment]
Already had some results: it's not working. The fix is not working.
I have a show with unaired episodes, and the default EP status set to Ignored. However, newly aired episodes are still downloaded. It is an ungoing season (The Big Bang Theory), could it be that currently the setting only will apply to new episodes, as in episodes that are not already listed? Or in other words, could it be that this will, currently, only kick in for new seasons?

**Comment by abeloin** [comment]
The 'Default Episode Status' is to set the initial status of missing episodes(or added episodes) dated before the current date and episodes without date. New episode dated in the future are always added as unaired and will change status to wanted around the specified date and time of the show.

If you don't want to download new episodes, activate the 'Paused' option in the show's settings

**Comment by IskanderNovena** [comment]
Well, that explains a lot. Might be better to rephrase the explanation on the Default EP status then, though, since the current line doesn't convey it's proper use (at least not to me): "(this will set a default status to be applied to any newly added episodes)"
Newly, to me, means 'recent', which I read as new episodes for the show, especially unaired ones.

**Comment by abeloin** [comment]
I understand the confusion and is something I will create pull request for.

**Comment by IskanderNovena** [comment]
Thanks. Then as far as I'm concerned, case closed ;)
