### ISSUE TITLE
Option to Never download specials

### ISSUE THREAD

**Issue by echel0n** [SiCKRAGETV/sickrage-issues#21]
<a href="https://github.com/ThePieMan"><img src="https://avatars.githubusercontent.com/u/4666630?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [ThePieMan](https://github.com/ThePieMan)**
_Thursday Nov 27, 2014 at 16:29 GMT_
_Originally opened as https://github.com/SiCKRAGETV/SickRage/issues/969 (5 comment(s))_

----

Specials, as the are released, are added into my backlog. It would be nice if there was a default option to mark any and all specials straight to Ignore. Thanks

**Comment by fernandog** [comment]
@TagForce can we add the "disable" feature in the SHOWUPDATER thread? Because in that thread that SR makes unaired > wanted, isn't?

**Comment by TagForce** [comment]
@fernandog I think it should already do this. But maybe newly downloaded episodes from the indexer have a status of UNKNOWN, in which case they will get set to default_ep_status... Also for season 0.

I'll have a possible fix in a minute.

**Comment by fernandog** [comment]
@ThePieMan

By default now, specials are set to SKIPPED
But If you DO want to download specials, go to your show and set them to WANTED.

**Comment by ThePieMan** [comment]
@fernandog Thanks. Is there somewhere in config that I could change this to default to IGNORED instead of SKIPPED?

**Comment by fernandog** [comment]
@ThePieMan no option

https://github.com/SiCKRAGETV/SickRage/pull/1594#issuecomment-83638077

**Comment by TagForce** [comment]
@markheloking @fernandog I think the real problem occurs when the following line returns False when it should be True:
elif self.airdate == datetime.date.fromordinal(1):
If this happens for a special, then the special will remain at status UNKNOWN, and it would skip everything and set it to WANTED because that's the default_ep_status.

@ThePieMan
Nope, the logic in the code says they should be set to SKIPPED. If you really want them to be ignored, then that would need to be added as a feature request. My PR is just a fix for (apparently) broken code :)

**Comment by fernandog** [comment]
@TagForce your PR fixed that or it's another issue in the code?

**Comment by ThePieMan** [comment]
Thanks @TagForce - at least they should be easy to find in Manage Episodes now, and not clutter up the backlog. Cheers!

**Comment by TagForce** [comment]
@fernandog My PR makes sure that it doesn't matter if that check is accurate or not for specials. I can't change the other condition because I have no idea why it doesn't work, or what should fix it. I can test it, but I'd have to wait for episodes to be added to shows for it to allow me to debug it.

@ThePieMan For the internal workings of SR it doesn't matter if Specials are Ignored or Skipped. They behave EXACTLY the same (don't count against total episodes or individual show episode counts, and are not downloaded). The only difference is the label and in which list they show up.

**Comment by markheloking** [comment]
As far as I know, this is still a problem (and an annoying one at that). I will report back if I find an example of it.
