### ISSUE TITLE
Home page show list appears unstyled before entire page loads

### ISSUE THREAD

**Issue by timgilbert** [SiCKRAGETV/sickrage-issues#2381]
Hi, I'm running SickRage on a mac mini, up to date from master, with homebrew python and mostly accessing it from Chrome.

I've got about 100 active shows, and it generally takes about 3 seconds for Chrome to paint the entire page. In the interim, the main `<table>` element constituting the show list appears as unstyled, like this:

![Unstyled show list](http://i.imgbox.com/iXWRGtwL.png)

Then when the entire page loads, the main show list suddenly becomes styled again, looking like this:

![Styled show list](http://i.imgbox.com/8SjXDBGo.png)

I'm assuming that this is because Chrome doesn't apply styles to the table until it sees the closing `</table>` element.

Anyways, it's kind of distracting, so I'm filing this bug. I guess the ideal thing would be to move from tables to divs or something, but I recognize that's probably not a simple undertaking. Alternately if the list of shows could be rendered more quickly, I guess that would help too.

**Comment by miigotu** [comment]
We are trying to avoid many webUI changes during the mako conversion. At first it will be a direct template conversion, and then we can worry about improving it once the kinks are worked out.

**Comment by OmgImAlexis** [comment]
@miigotu would you be okay if I started converting more of it over to templates and away from javascript functions to style the page, etc?

**Comment by miigotu** [comment]
@OmgImAlexis if you mean to help porting to mako yes. The current templates are in a sort of freeze state as they will be replaced with the mako templates and we don't want to miss fixes we made in cheetah templates in the mako templates.

The start of mako is in the mako branch, as we finish each .mako template file we will be removing it's .tmpl counterpart (to keep track of the finished templates).

Technically we hope to remove as much SQL, js and python from the templates as possible.

I think it would be easiest to port the templates to mako as is first though, you can see what it takes to convert from cheetah to mako in https://github.com/SiCKRAGETV/SickRage/commit/ee03e01f6bbda5182cf69935d99751036aeb1f2b
and https://github.com/SiCKRAGETV/SickRage/commit/bbccc38ebbe3baa288d0fe698a75419ec5dcb508 (incomplete)

**Comment by WebSpider** [comment]
@timgilbert we changed a lot with regards to page loading, can you see if this issue still exists in current master?

**Comment by timgilbert** [comment]
Thanks @WebSpider. With the latest master the situation is improved, but I'm still seeing unstyled content for about 2.5 seconds before it is completed. 

I have tested a little more and noticed that the problem only occurs on Chrome (latest) - Firefox and Safari seem to render the table with correct styles as they go.

**Comment by WebSpider** [comment]
Good to see we're on the right track. This will further be improved by #2502 and #2503

**Comment by OmgImAlexis** [comment]
@timgilbert could you please load up Sickrage, open the network tab in developer tools and comment a [gist](https://gist.github.com) with the HAR contents?

"Copy ALL as HAR" is the one you want.

![screen shot 2015-08-21 at 11 35 06 pm](https://cloud.githubusercontent.com/assets/6525926/9410070/519b151c-485d-11e5-973f-c773ea4ceb59.png)

**Comment by timgilbert** [comment]
Well, the HAR comes out to about 16MB, which is big enough that it crashes gist. I've gzipped it and uploaded it to tinyupload here:

http://s000.tinyupload.com/index.php?file_id=73769741275455516012

**Comment by OmgImAlexis** [comment]
Thanks, it was as I thought. The images seem to stop the page loading.

@miigotu @WebSpider thoughts on lazy loading the images? That's what's causing the styling issues, since it's downloading the images it has to wait to render the page. If we load the page and then lazy load the images it should fix that.

**Comment by neoatomic** [comment]
Do you want to keep this open, or can i close it.?

**Comment by miigotu** [comment]
@neoatomic it still has the issue.

**Comment by WebSpider** [comment]
@MGaetan89 Feel like looking at this too?

**Comment by OmgImAlexis** [comment]
@timgilbert can you switch to the develop branch and check, it should be fixed now.

The only other thing that could be causing this is that the CSS must be after some js that's stopping the page from rendering.

**Comment by MGaetan89** [comment]
@WebSpider I think this issue will get fix on its own with the work @OmgImAlexis and I are doing with the CSS/JS. We already made some progress in the latest release.
Let's see if that helped @timgilbert ;)

**Comment by timgilbert** [comment]
Sorry for the late reply, all. I checked out develop and am still seeing the same issue there. The page does load faster, and I only see the unstyled version of the table for a brief amount of time, but it's still pretty noticeable.

In case it's helpful, I uploaded another `.har` file, this time from the develop branch as of right now here: http://s000.tinyupload.com/index.php?file_id=15482521073853677983

**Comment by miigotu** [comment]
@OmgImAlexis can you check this new hat?

**Comment by OmgImAlexis** [comment]
@miigotu will do, @timgilbert thanks.

**Comment by OmgImAlexis** [comment]
Okay I've had a look at the only thing I can think of now is that either he's not got enough ram and Chrome's having issues loading the js and css at the same time or there must still be some js files being called before the CSS.

**Comment by timgilbert** [comment]
Well, this is a 2011 Mac Mini, so not blazing fast, but it's got 8GB RAM with usually nothing running save Chrome, Kodi, and SickRage. Right now it's in its usual state and Activity Monitor is reporting about 3.5GB of free memory. The OS and apps are running off of an SSD, too, FWIW.

It's definitely a Chrome-specific issue though. I might just use Firefox instead for now but I'm happy to keep testing this issue if it's helpful.

One thing has changed since the last time I looked into this, which is that the logo images are coming across as empty in the few seconds before table colors are applied to the show list. It's a little hard to get a screenshot, but here's a corner of the unstyled page:

![screen shot 2015-09-05 at 1 01 19 am](https://cloud.githubusercontent.com/assets/94482/9697781/c51cddd8-5369-11e5-835f-81cda830888b.png)

This would seem to be evidence against the logo images blocking the styles from being applied, at least.

**Comment by miigotu** [comment]
@timgilbert the images are loaded after the page loads now, specifically trying to fix the issue. imho its worse this way because the "unstyled" page before was just the table position, and now its the table position being off and the images also being missing.

**Comment by OmgImAlexis** [comment]
@timgilbert that setup should be fine and is actually complete overkill compared to my testbox. I'm still unsure exactly what's causing this. Could you try loading this in incognito mode, the only other thing that may be causing this is a Chrome extension and that may explain why it only seems to be happening on Chrome.

**Comment by timgilbert** [comment]
I get the same results in incognito mode. (I don't have many extensions installed anyways and have disabled AdBlock on the SickRage hostname/port.)

**Comment by OmgImAlexis** [comment]
@timgilbert any chance you could port forward this and let me have a look at it? I'd suggest you setup the login info(so you don't get randoms accessing it) and send me the details via email, check my github profile for my email. I really have no idea what may be causing this now.

**Comment by timgilbert** [comment]
@OmgImAlexis sure, I can do that, though I won't have time to set it up until Monday at the earliest. I'll shoot you an email when I'm about to start working on it.

**Comment by OmgImAlexis** [comment]
@timgilbert alright sounds good. I'd love to get to the bottom of this. I suspect you're a weird edge case and that's why we haven't seen this before or people are just too lazy to submit issues when they come across them. I'm guessing https://github.com/SiCKRAGETV/sickrage-issues/issues/2657#issuecomment-137922129 will probably help with this aswell as the other imporvements @MGaetan89 and I are doing with the js and css loading.

**Comment by fernandog** [comment]
/home with 80 shows
Load time: 0.5080s / Mako: 0.5012s

this unstyled things last like .2 seconds.

**Comment by OmgImAlexis** [comment]
@timgilbert since we've changed a LOT in the last day can you try the newest dev commit please.

**Comment by timgilbert** [comment]
I checked out the develop branch and this is fixed there. Nice job!

I do still see the unstyled content for maybe a second the very first time I pull up the page after clearing the cache, but every time after that, the CSS seems to be cached so if I reload the page the table shows up as styled as it renders (with the alternating colors etc).

Thanks again for the help! I think this issue can be closed now.
