### ISSUE TITLE
Backlog overview page won't load, and slow webui in general.

### ISSUE THREAD

**Issue by strike84** [SiCKRAGETV/sickrage-issues#2388]
SR Version:	BRANCH: (master) / COMMIT: (23f36256e8af9383f4bc80ca3b2aca75148a8694)
Python Version:	2.7.10 (default, May 23 2015, 09:40:32) [MSC v.1500 32 bit (Intel)]
OS: Windows 7
What I did: Tried to load the backlog overview page in the webui.
What happened: Ended up on the shows page instead with error below.
```
2015-07-29 19:48:58 Thread-60 :: Failed doing webui callback: Traceback (most recent call last):

  File "C:\SickRage\sickbeard\webserve.py", line 273, in async_call
    result = function(**kwargs)
  File "C:\SickRage\sickbeard\webserve.py", line 3119, in backlogOverview
    [curShow.indexerid])
  File "C:\SickRage\sickbeard\db.py", line 192, in select
    sqlResults = self.action(query, args, fetchall=True)
  File "C:\SickRage\sickbeard\db.py", line 169, in action
    sqlResult = self.execute(query, args, fetchall=fetchall, fetchone=fetchone)
  File "C:\SickRage\sickbeard\db.py", line 85, in execute
    return self._execute(query, args).fetchall()
  File "C:\SickRage\sickbeard\db.py", line 236, in _unicode_text_factory
    return unicode(x, sickbeard.SYS_ENCODING,errors="ignore")
  File "C:\Python27\lib\encodings\cp1252.py", line 15, in decode
    return codecs.charmap_decode(input,errors,decoding_table)
MemoryError
```
Also the webui has been extremely slow recently, takes 20-30 sec to load a page.

**Comment by neoatomic** [comment]
The log shows a memory error.

Check the seize of your sickbeard.db. There where some problems with special characters causing the DB to get very large. Check the news page inside SickRage for more info.

**Comment by strike84** [comment]
How do I fix the memory error? 
My sickbeard.db is 2,53 GB, is that a normal size? I'm doing a FULL update on all the shows now to see if that helps. But I don't have any special characters in any of my files, I think... I will check tho, and do a mass rename.

**Comment by neoatomic** [comment]
No thats way to large. ;)
Yes, use mass update to do a full update of all shows, that should fix it.

**Comment by strike84** [comment]
I tried doing mass update of the shows, but that didn't change anything. Sickbeard.db are still the same size, webui is still slow and I get the same error when I try to access the backlog overview page.

**Comment by miigotu** [comment]
You can try to run this sql on your database (with SR stopped)

sqlite3 sickbeard.db
```sql
UPDATE tv_episodes SET description = '' WHERE length(description) > 800;
```

**Comment by fernandog** [comment]
@miigotu cant we do this in db sanity check?

**Comment by miigotu** [comment]
I'm not sure what the max length should be yet, the longest description in my test db was 783

**Comment by miigotu** [comment]
Lol, and on my main machine I have a description that is 3211 characters long wtf.

**Comment by miigotu** [comment]
And, that 3211 is valid description, for the smurfs and the magic flute...

**Comment by strike84** [comment]
@miigotu Can you please explain a bit more on your previous post. :) How do I run this sql thingy..?

**Comment by miigotu** [comment]
Stop SR, open a terminal, cd to where your sickrage .db is, and type `sqlite3 sickbeard.db`
In the sqlite3 command line, type 
`UPDATE tv_episodes SET description = '' WHERE length(description) > 1000;`
press ctrl+d
start SR

Full update on shows.

**Comment by strike84** [comment]
Yeah, that's what I tried the first time, bur it didn't work. That's why I asked, thought I was doing something wrong.. "'sqlite3' is not recognized as an internal or external command, operable program or batch file.

**Comment by miigotu** [comment]
try just sqlite
windows or linux?

**Comment by strike84** [comment]
Windows, sqlite didn't work either..

**Comment by miigotu** [comment]
https://www.sqlite.org/2015/sqlite-shell-win32-x86-3081101.zip

**Comment by strike84** [comment]
Thanks! ctrl+d didn't work.. I just typed "UPDATE tv_episodes SET description = '' WHERE length(description) > 1000;" and hit enter. Should I do anything else or just close the command line and start SR and do full update?

**Comment by strike84** [comment]
I must have done something right, cause backlog overview page is back. And it seems like the webui responds a lot faster,maybe even as fast as it was .. I'm running full update on shows now, hope that shrinks sickrage.db to a normal size.

**Comment by strike84** [comment]
Guess I spoke to soon.. Accessed backlog overview 3-4 times. And now it spits out the same memory error again. Maybe it goes away when I'm finished updating the shows..

**Comment by strike84** [comment]
sickrage.db is still the same size. I do have 200 shows tho, so I'm not sure what normal size would be. Backlog overview page comes and goes, it loads now, but sometimes I get the memory error. The webui responds a bit better now but sometimes it takes 5-10 sec again for a page to load, but it's better than what is was.

**Comment by WebSpider** [comment]
You should be able to make the DB size smaller like this:

Stop SR, open a terminal, cd to where your sickrage .db is, and type 
```sqlite3 sickbeard.db```
In the sqlite3 command line, type
```VACUUM;```
Press ctrl+D to exit sqlite3
Check size of your DB.

**Comment by strike84** [comment]
That worked, now the DB is 155MB. But the webui still doesn't responds as fast as it used to and backlog overview page is still buggy, I loaded it 4 times now without problem and then the 5th time memory error.

**Comment by neoatomic** [comment]
See if the cache folder is also to large. If so rename/remove the folder and let SickRage build a new cache folder.

**Comment by miigotu** [comment]
Also delete cache.db

**Comment by strike84** [comment]
Nah, cache folder is only 274MB, I'm guessing that's not to bad? Any other suggestions? It looks like the magic number is 3 or 4 before I get the memory error, that is I can access backlog overview 3 or 4 times before I get the error. I can't remember if the problem goes away after a while or if I have to restart SR to get access again, but I'll check that.

OT: Please don't stop update the news page or the changelog in SR. :)

**Comment by miigotu** [comment]
News is for important info only.
Changelog maintainer is on vacation.

**Comment by WebSpider** [comment]
@miigotu how can I help out with the changelog?

**Comment by fernandog** [comment]
@WebSpider PR to https://github.com/SiCKRAGETV/sickrage-news/blob/gh-pages/CHANGES.md

use the links in there and update the values to see the diffs

@duramato added things in order: added. changed, fixed, etc.
