### ISSUE TITLE
Can't connect to IPT or TD

### ISSUE THREAD

**Issue by kendog819** [SiCKRAGETV/sickrage-issues#2656]
![image](https://cloud.githubusercontent.com/assets/11353628/9697773/4fc6ace4-5369-11e5-99c7-494c79ad0605.png)

![image](https://cloud.githubusercontent.com/assets/11353628/9697768/3c5b1e42-5369-11e5-8c9c-5575a5162f95.png)

This just started happening within the last couple days. Not sure what is going on, or if it is something I can fix. "Verify SSL" is UNchecked also. Running on a QNAP NAS.

Thanks,
Ken

**Comment by miigotu** [comment]
@kendog819 have you tried the develop branch? it is fixed there and will be merged to master tonight or tomorrow.

**Comment by kendog819** [comment]
![image](https://cloud.githubusercontent.com/assets/11353628/9768726/85433d46-56f3-11e5-91f4-a4ec127cffe7.png)

Still having issues...

**Comment by kendog819** [comment]
@miigotu Can you please stop closing my threads until they are verified as actually fixed

![image](https://cloud.githubusercontent.com/assets/11353628/9793673/a9802efa-57b4-11e5-89c5-c08274803151.png)

**Comment by miigotu** [comment]
Can you please stop opening duplicate threads that already exist? Do some searching and you will see that #1 you are using the wrong SR package, and 2 you can disable SSL verify. IPT and TD WORK.

**Comment by kendog819** [comment]
Can you please resolve an issue before closing a thread, so that I don't need to open another thread to be seen by people?

My 1st post clearly states SSL is disabled.
