### ISSUE TITLE
Error updating to latest version. Path spec master not known

### ISSUE THREAD

**Issue by udochrist** [SiCKRAGETV/sickrage-issues#2792]
Hi,
I'm on SR Version:	BRANCH: (master) / COMMIT: (7694b70047796dc0c9c812300a090f78a4240f46) 

And am trying to update. This fails and the log shows:

    2015-09-13 12:25:16 ERROR    Thread-13 :: "/usr/local/git/bin/git" submodule update --init --recursive --force master returned : error: pathspec 'master' did not match any file(s) known to git.

Seems like something in the github repo is not as expected?

**Comment by flightlevel** [comment]
There was a small problem earlier which has been fixed now 7694b70047796dc0c9c812300a090f78a4240f46
Have you tried restarting SR?

**Comment by udochrist** [comment]
Indeededly so. Solved itself

**Comment by fdamstra** [comment]
I'm still getting this issue.

When I ran into problems earlier today, I followed the command-line instructions on the main issues page ( https://github.com/SiCKRAGETV/sickrage-issues ), and the line 'git checkout master' gives this same error: "error: pathspec 'master' did not match any file(s) known to git."

Everything in General Settings->Advanced points to 'master' (and reset is checked), but the WebUI still shows "You're using the develop branch. Please use 'master' unless specifically asked"

**Comment by flightlevel** [comment]
@udochrist 
Did you try restarting SR?

**Comment by udochrist** [comment]
Yes.

**Comment by flightlevel** [comment]
Oops, meant @fdamstra

**Comment by OmgImAlexis** [comment]
@flightlevel @fdamstra if this happens just keep doing an update, restart until it fixes itself. It should take a maximum of 2 updates and restarts. If there's still an issue after that then let us know otherwise this is staying closed.

**Comment by miigotu** [comment]
@fdamstra your issue is different. seems you don't have a master branch.
do this:

```bash
git fetch origin
git checkout -b master origin/master
```

**Comment by fdamstra** [comment]
Thank you. That appears to have resolved the issue.
