### ISSUE TITLE
IMDB View Popular shows broken.

### ISSUE THREAD

**Issue by AubreyKloppers** [SiCKRAGETV/sickrage-issues#2830]
After reboot yesterday (and upgrade) I get:
__*Fetching of IMDB Data failed. Are you online?
Exception:
'NoneType' object has no attribute 'contents'*__

I know it was logged before, but was fixed, so this is new...
Nothing in LOGS to point to any problems

Additional Info:
* CACHE cleared.
* SickRage restarted.
* System rebooted.
* IMDB images does get created in the cache images directory
* "wget http://www.imdb.com/search/title?at=0&sort=moviemeter&title_type=tv_series&year=2014,2016"
downloads:
* __"-rw-r--r-- 1 root root 184201 Sep 16 11:08 title?at=0"__ 
the content of the file is the content of the IMDB page.

This seems/feels to be just a timing-thing...

**Comment by mariothiel** [comment]
Its also broken for me
the log says:
```
2015-09-16 10:57:04 WARNING  Thread-666 :: Connection error to getURL http://www.imdb.com/search/title?at=0&sort=moviemeter&title_type=tv_series&year=2014,2016 Error: error HTTPConnectionPool(host='www.imdb.com', port=80): Read timed out
```

**Comment by AubreyKloppers** [comment]
Doing a "wget wget http://www.imdb.com/search/title?at=0&sort=moviemeter&title_type=tv_series&year=2014,2016" on the server gets me a file called:
"-rw-r--r-- 1 root      root   184201 Sep 16 11:08 title?at=0"
the content of the file is the content of the IMDB page, so it is not a connection problem...

**Comment by Miyamoto65** [comment]
Same for me, (just did the update as well).   I don't know where to see the errors you are seeing, but the "Logs and Errors" dropdown doesn't show an error.. just the same 
Fetching of IMDB Data failed. Are you online?
Exception: 
'NoneType' object has no attribute 'contents'

**Comment by neoatomic** [comment]
Looks like IMDB is blocking.

![naamloos](https://cloud.githubusercontent.com/assets/7928052/9902129/4a264522-5c6c-11e5-873d-508c201605dc.png)

**Comment by AubreyKloppers** [comment]
@neoatomic - I can see that IMDB is NOT blocking if I do get the file with the shows and the images downloaded using the SickRage server console.  It feels like it is a timing thing, almost that the error is an arbitrary error, that gets returned before all the data has been pulled from IMDB...

**Comment by Miyamoto65** [comment]
Blocking all of us or just me?.... and didn't I read somewhere we were switched from IMDB to TVDB?
(Ps It worked a bit yesterday but no idea how/why or how to reproduce.)

**Comment by neoatomic** [comment]
@jonathanendersby Want to take a look.?

**Comment by fernandog** [comment]
Fetching of IMDB Data failed. Are you online?
Exception:
'NoneType' object has no attribute 'contents'

**Comment by miigotu** [comment]
This is a python error in SR. I will look.

**Comment by kailia** [comment]
+1

**Comment by neoatomic** [comment]
Should be fixed now. Can someone test.?

**Comment by mariothiel** [comment]
I just did... I still get an error but nothing comes up in the log:

> Fetching of IMDB Data failed. Are you online?
> Exception: 
> 'NoneType' object has no attribute 'groups'

**Comment by neoatomic** [comment]
@mariothiel did you update.?

**Comment by mariothiel** [comment]
I just did a manual pull it 136 files changed. Still the same error though. Maybe do a complete new clone??

**Comment by miigotu** [comment]
@mariothiel did you restart SR after git pull?

`'NoneType' object has no attribute 'groups'` is not possible in imdbPopular.py anymore

**Comment by mariothiel** [comment]
No Sir, I did not! And yes that was the problem, function works now. Thank you guys!

 

Von: miigotu [mailto:notifications@github.com] 
Gesendet: Montag, 21. September 2015 17:40
An: SiCKRAGETV/sickrage-issues
Cc: Mario
Betreff: Re: [sickrage-issues] IMDB View Popular shows broken. (#2830)

 

@mariothiel <https://github.com/mariothiel>  did you restart SR after git pull?

'NoneType' object has no attribute 'groups' is not possible in imdbPopular.py anymore

**Comment by fernandog** [comment]
it's working for me. thanks

**Comment by AubreyKloppers** [comment]
Just tested and THANK YOU! Working 100%!
