### ISSUE TITLE
Torcache Failing unless Referer header set to URL

### ISSUE THREAD

**Issue by wuench** [SiCKRAGETV/sickrage-issues#2837]
All torrent downloads on torcache fail unless the Referer header is set to: 
Referer: hxxp://torcache.net/torrent/HASH.torrent

Noticed these errors in log for all torcache downloads:
2015-09-16 18:14:52 WARNING  SEARCHQUEUE-DAILY-SEARCH :: Could not download hxxp://torcache.net/torrent/HASH.torrent

What I did:
Opened link in fiddler, saw two request/response pairs.  The second had the referrer set to hash URL.  I edited the first request in fiddler and added the response header and it succeded.
Also verified with Chrome's Modify Headers extension.

Info:
SR Version:	BRANCH: (master) / COMMIT: (b7edb8a61473b140f002bea11174af47ab738bbb) 
Python Version:	2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit (AMD64)]
OS: Win7 64 Bit

**Comment by wuench** [comment]
Here is my dirty fix for now...  in /SickRage/SickBeard/Providers/generic.py

>  logger.log(u"Downloading a result from " + self.name + " at " + url)
         # --- BEGIN EDIT ----
	    if "torcache" in url:
                logger.log(u"Torcache URL Detected, adding Referer")
                self.headers.update({'Referer': url})

**Comment by duramato** [comment]
@wuench this is already fixed

**Comment by wuench** [comment]
I just downloaded the latest release today and it was not fixed.

**Comment by fernandog** [comment]
Wait next release

@miigotu can you hotfix please?

**Comment by wuench** [comment]
Ok thanks.  Sorry, my GIT-fu is lacking. :)
