### ISSUE TITLE
cannot concatenate 'str' and 'exceptions.TypeError' objects

### ISSUE THREAD

**Issue by fernandog** [SiCKRAGETV/sickrage-issues#287]
Tried to open an issue with "Submit Errors"
BUT I could not find the error in the LOG.
Maybe this happened because SR could not found it as the error was from 8 hours ago and last logger line as from 5 hours.

SR Version:	BRANCH: (develop) / COMMIT: (8b84e4f4bc6cdebdc605438e9e75d15f1133d65e) 
SR Config file:	/home/pi/SickRage/config.ini
SR Database file:	/home/pi/SickRage/sickbeard.db
SR Cache Dir:	/home/pi/SickRage/cache
SR Arguments:	['-q', '--daemon', '--nolaunch', '--pidfile=/var/run/sickrage/sickrage.pid', '--datadir=/home/pi/SickRage']
SR Web Root:	
Python Version:	2.7.3 (default, Mar 18 2014, 05:13:23) [GCC 4.6.3]

```python
2014-12-25 08:40:56 ERROR    Thread-19 :: cannot concatenate 'str' and 'exceptions.TypeError' objects
Traceback (most recent call last):
  File "/home/pi/SickRage/sickbeard/logger.py", line 192, in submit_errors
    issue = gh.get_organization(gh_org).get_repo(gh_repo).create_issue("[APP SUBMITTED]: " + curError.title, message)
TypeError: cannot concatenate 'str' and 'exceptions.TypeError' objects
2014-12-25 08:41:10 ERROR    Thread-49 :: cannot concatenate 'str' and 'exceptions.TypeError' objects
Traceback (most recent call last):
  File "/home/pi/SickRage/sickbeard/logger.py", line 192, in submit_errors
    issue = gh.get_organization(gh_org).get_repo(gh_repo).create_issue("[APP SUBMITTED]: " + curError.title, message)
TypeError: cannot concatenate 'str' and 'exceptions.TypeError' objects
2014-12-25 08:41:12 DEBUG    TRAKTCHECKER :: Starting new thread: TRAKTCHECKER
2014-12-25 08:41:12 DEBUG    TRAKTCHECKER :: Starting trakt show watchlist check
2014-12-25 08:41:15 DEBUG    CHECKVERSION :: Starting new thread: CHECKVERSION
2014-12-25 08:41:15 INFO     CHECKVERSION :: Checking for updates using GIT
2014-12-25 08:41:15 DEBUG    CHECKVERSION :: Executing git symbolic-ref -q HEAD with your shell in /home/pi/SickRage
2014-12-25 08:41:15 DEBUG    CHECKVERSION :: git output: refs/heads/develop
2014-12-25 08:41:15 DEBUG    CHECKVERSION :: git symbolic-ref -q HEAD : returned successful
2014-12-25 08:41:15 DEBUG    CHECKVERSION :: Executing git rev-parse HEAD with your shell in /home/pi/SickRage
2014-12-25 08:41:15 DEBUG    CHECKVERSION :: git output: 8b84e4f4bc6cdebdc605438e9e75d15f1133d65e
2014-12-25 08:41:15 DEBUG    CHECKVERSION :: git rev-parse HEAD : returned successful
2014-12-25 08:41:15 DEBUG    CHECKVERSION :: Executing git config remote.origin.url https://github.com/SiCKRAGETV/SickRage.git with your shell in /home/pi/SickRage
2014-12-25 08:41:15 DEBUG    CHECKVERSION :: git output: 
2014-12-25 08:41:15 DEBUG    CHECKVERSION :: git config remote.origin.url https://github.com/SiCKRAGETV/SickRage.git : returned successful
2014-12-25 08:41:15 DEBUG    CHECKVERSION :: Executing git fetch origin with your shell in /home/pi/SickRage
2014-12-25 08:41:17 ERROR    Thread-51 :: cannot concatenate 'str' and 'exceptions.TypeError' objects
Traceback (most recent call last):
  File "/home/pi/SickRage/sickbeard/logger.py", line 192, in submit_errors
    issue = gh.get_organization(gh_org).get_repo(gh_repo).create_issue("[APP SUBMITTED]: " + curError.title, message)
TypeError: cannot concatenate 'str' and 'exceptions.TypeError' objects
```

**Comment by fernandog** [comment]
@echel0n it's a nice feature that it's not working (auto submit issue)

**Comment by fernandog** [comment]
@abeloin can you check this one?  I coudln't fix it

**Comment by abeloin** [comment]
@fernandog WIll do.

At first glance I would say it's missing str() around curError.title.

**Comment by abeloin** [comment]
@fernandog Should be working with this pull request

**Comment by fernandog** [comment]
nice! thanks!

**Comment by TehWardy** [comment]
I believe this is still broken ... After clean install from master branch yesterday I am still able to replicate this problem.

**Comment by fernandog** [comment]
develop branch. not master.

**Comment by TehWardy** [comment]
Ok confirmed, just pulled the develop branch still getting this issue.

**Comment by TehWardy** [comment]
Here's my current log ...

2015-02-01 16:52:56 Thread-41 :: cannot concatenate 'str' and 'exceptions.TypeError' objects
2015-02-01 16:49:18 Thread-39 :: cannot concatenate 'str' and 'exceptions.OSError' objects
2015-02-01 16:19:38 DAILYSEARCHER :: MD5 hash does not match: C36513DE5AC7A65134D6B85B6BD29C45 File: 537FC41E67D5E644EC8E330F770F981D
2015-02-01 16:19:38 MAIN :: Unable to save the file: error 2 : No such file or directory

**Comment by fernandog** [comment]
FULL logs please. Also commit hash and etc.

**Comment by TehWardy** [comment]
Uh that's all there was in the UI (I copied from the error log page in to here).
Is there some way I can grab a full debug trail with a stack trace for you guys when this stuff happens ... i'm a C# programmer, this python stuff is a little out of my world.

**Comment by fernandog** [comment]
/SickRage/Logs/sickrage.log

**Comment by TehWardy** [comment]
Ok so here's the chunk that relates to this error ... 

2015-02-01 19:38:39 ERROR    Thread-51 :: cannot concatenate 'str' and 'exceptions.KeyError' objects
Traceback (most recent call last):
  File "/share/MD0_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/sickbeard/logger.py", line 192, in submit_errors
    issue = gh.get_organization(gh_org).get_repo(gh_repo).create_issue("[APP SUBMITTED]: " + curError.title, message)
TypeError: cannot concatenate 'str' and 'exceptions.KeyError' objects

...
Sick rage has been adding terrabytes to my sab queue so I doubt you want all the logs.

**Comment by TehWardy** [comment]
2015-02-01 19:46:21 ERROR    Thread-66 :: cannot concatenate 'str' and 'exceptions.TypeError' objects
Traceback (most recent call last):
  File "/share/MD0_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/sickbeard/logger.py", line 192, in submit_errors
    issue = gh.get_organization(gh_org).get_repo(gh_repo).create_issue("[APP SUBMITTED]: " + curError.title, message)
TypeError: cannot concatenate 'str' and 'exceptions.TypeError' objects

**Comment by fernandog** [comment]
Are you sure you are using develop??

**Comment by abeloin** [comment]
@fernandog Pull request SiCKRAGETV/SickRage#1233 is yet to be merge in develop.

**Comment by TehWardy** [comment]
I went in to the options area of sickrage and in the bit on git selected the develop branch then hit the button.

It took its time restarting it seemed to work fine doing that on its own ...
Under help and info it says: 

     BRANCH: (develop) / COMMIT: (c62d8f2c799edd7daad5648f45276a3464d83a9e) 

Is this correct version?
If not how do I force an update to the correct version?
