### ISSUE TITLE
List of qualities (custom options) not showing up

### ISSUE THREAD

**Issue by daveyboy37** [SiCKRAGETV/sickrage-issues#2887]
Since installing the last updates, nothing seems to happen when selecting custom for show quality.
No box opening up to actually choose initial and preferred qualities.

**Comment by fernandog** [comment]
@MGaetan89 can you check this please?

**Comment by Jeffoz** [comment]
Indeed, but next to this when you click "edit" on a show it also takes your back to the show list. So you can't edit the quality there as well.

**Comment by MGaetan89** [comment]
I have the issue too. I will see if I can find the reason and fix it.

**Comment by Jeffoz** [comment]
Also have errors downloading now that Sickrage will say he doesn't want an episode with a certain quality while everything is selected now by default.

**Comment by Drempelaar** [comment]
Same here. Nor is it able to update the custom setting in mass update

**Comment by miigotu** [comment]
@OmgImAlexis linted all of the js yesterday: https://github.com/SiCKRAGETV/SickRage/pull/2550

**Comment by miigotu** [comment]
SR snatches fine here. Custom quality is messed up though I see. I'll have a look but might need to wait for @OmgImAlexis

**Comment by miigotu** [comment]
@OmgImAlexis will need to double check types everywhere equality operator was swapped for identity operator in js.

**Comment by stacimail** [comment]
Can now choose "custom" and change the options when adding a new show with success, thank you. However, still having same issue as Jeffoz: "when you click edit on a show it also takes your back to the show list." Error logged is:

2015-09-21 11:24:26 Thread-36 :: Failed doing webui callback: Traceback (most recent call last):
  File "/volume1/@appstore/sickrage/var/SickRage/sickbeard/webserve.py", line 274, in async_call
    result = function(**kwargs)
  File "/volume1/@appstore/sickrage/var/SickRage/sickbeard/webserve.py", line 1315, in editShow
    t = PageTemplate(rh=self, file="editShow.mako")
  File "/volume1/@appstore/sickrage/var/SickRage/sickbeard/webserve.py", line 115, in __init__
    super(PageTemplate, self).__init__(*args, **kwargs)
  File "/usr/local/sickrage/var/SickRage/lib/mako/template.py", line 321, in __init__
    module = self._compile_from_file(path, filename)
  File "/usr/local/sickrage/var/SickRage/lib/mako/template.py", line 379, in _compile_from_file
    module = compat.load_module(self.module_id, path)
  File "/usr/local/sickrage/var/SickRage/lib/mako/compat.py", line 66, in load_module
    return imp.load_source(module_id, path, fp)
  File "/usr/local/sickrage/var/cache/mako/usr/local/sickrage/var/SickRage/gui/slick/views/editShow.mako.py", line 21, in 
    from sickbeard import exceptions
ImportError: cannot import name exceptions

**Comment by daveyboy37** [comment]
Mmmm. Not seeing that here before or after the fix.

**Comment by miigotu** [comment]
Stop SR, delete cache/mako folder and start SR again.

**Comment by stacimail** [comment]
Stopped, deleted cache/mako, started SR and same issue. Will uninstall/reinstall and try again.

**Comment by stacimail** [comment]
Complete reinstall, no change. Another error is logged when hitting "pause" button as well, on top of log attached (bottom error is logged when pressing "edit" in show). 

Since this is a fresh install, wondering are there any leftover files elsewhere on the machine that might cause this?
<img width="1120" alt="screen shot 2015-09-21 at 11 48 16 am" src="https://cloud.githubusercontent.com/assets/10871411/9998477/e2c686b4-6056-11e5-88f4-e57fa8d5d88e.png">

**Comment by fernandog** [comment]
please add github user pass in SR and use submit error feature

**Comment by stacimail** [comment]
Ok done, issue #2892 submitted

**Comment by fernandog** [comment]
The import name exceptions issue is fixed? You close it

**Comment by stacimail** [comment]
No, import named exceptions issue is not fixed, should be first comment in issue #2892

**Comment by OmgImAlexis** [comment]
@miigotu we should be using either `0` or actually testing what we're expecting instead of using `==` everywhere. `===` is faster and can prevent dev errors. What type should `preset` be?
