### ISSUE TITLE
iCal / webcal / Calendar feature not functional

### ISSUE THREAD

**Issue by timrettop** [SiCKRAGETV/sickrage-issues#330]
Branch: Master
Commit Hash: 33e95870e0c1b241c93f541d4ee27ed6ba3bfcb8
Environment: Ubuntu 14.04 Python 2.7.6

I was trying to add the SR webcal feed to google, and wasn't having much success with it.  I noticed that the logs were not indicating that google is even trying to parse the feed (as I expected to see "Receiving iCal request from" as the logger indicated). 

I tried locally as well, subscribing to the ical URL with my Calendar app and it would indicate that the URL is invalid.  So I dug further.  I noticed that back before Dec 8th, there was a function routing web calls to /api and /calendar  however, it looks like as a part of the checkin 589b7167c196ea5ff41315f915ab1ea6b28f3bdb  that was removed. 

Am I completely wrong, or is there no handling of the /calendar URI?

**Comment by JSKershaw** [comment]
This problem is also in the DEV build
BRANCH: (develop) / COMMIT: (8b84e4f4bc6cdebdc605438e9e75d15f1133d65e) 
Python Version:	2.7.3

**Comment by abeloin** [comment]
@timrettop It's in WebRoot class.

Try calling the calendar directly in a browser: http://sickrage.local:8081/calendar

**Comment by timrettop** [comment]
@abeloin that URL is locked behind the authentication layer that was added a ways back, and doesn't allow for iCal devices/services to access it. 

Thanks for the suggestion though.

**Comment by abeloin** [comment]
@timrettop @JSKershaw See issue SiCKRAGETV/sickrage-issues#456 it include a fix that will be merge in develop.

**Comment by fernandog** [comment]
@timrettop  please update SR and report back please. Fix was merged

**Comment by bobloadmire** [comment]
I still can't get this to work. I added the calendar to my google calendar, but the entire calendar is blank through today until 2016.

**Comment by abeloin** [comment]
@bobloadmire You should open a new issue. Check if it is locally: http://sickrage.local:8081/calendar and if you allowed in your firewall(router) access to the port from the Internet.
