### ISSUE TITLE
[APP SUBMITTED]: 'NoneType' object has no attribute 'replace'

### ISSUE THREAD

**Issue by Peanut-Afl** [SiCKRAGETV/sickrage-issues#3539]
### INFO
Python Version: **2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit (AMD64)]**
Operating System: **Windows-Vista-6.0.6002-SP2**
Branch: **master**
Commit: SiCKRAGETV/SickRage@533d8c1a0b2b20ed7c52dff3dbc3fc6b4eefa0a1
Link to Log: https://gist.github.com/d018416eb82b5bab92a4
### ERROR
```
SHOWQUEUE-ADD :: Error searching dir for episodes: 'NoneType' object has no attribute 'replace'
```
---
_STAFF NOTIFIED_: @SiCKRAGETV/owners @SiCKRAGETV/moderators

**Comment by SiCKRAGEB0T** [comment]
## Thanks for the bug/issue report
Please make sure to submit all of the [required information](https://github.com/SiCKRAGETV/sickrage-issues/blob/master/README.md), or we won't be able to help you!
Provide as **much** information as you can such as debug logs, commit hash, and tell us how to replicate the problem.For basic **questions** use the [ [forum] ](https://sickrage.tv/forums/), and for **Feature Requests** [ [Feathub] ](http://feathub.com/SiCKRAGETV/SickRage)
Also make sure the title accurately describes your issue. ("SR not working" etc. is not ok!)

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [x] Post debug logs, either inline (for smaller logs) or using gist)

## Many issues can simply be solved by:
- Making sure you update to the latest version.
- Have you tried turning your device off and on again?
- Using the **search** function to see if this issue has already been reported/solved.
- Do a [GIT reset](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#update-problems-try-this).
- Checking the [ [Wiki] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki) for [ [Guides] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Installation-&-Configuration-Guides), [ [FAQS] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes) [ [Main settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Settings-explained), [ [Show settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Show-settings-explained) [ [Remaining settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Remaining-settings-explained)
- Shutting down SickRage and removing the `cache/mako` & `cache/sessions` folders.
- If SickRage doesnt find any episodes you probably need to :
 - add a [Scene Exception](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Scene-exceptions-and-numbering)
 - Set the [Default Episode Status](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#newly-aired-shows-are-not-downloading-and-set-to-skippedignored) to `WANTED`
 - Make sure you understand how [quality detection](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Quality-Settings#quality-detectiondetermination) works during searches.
 - Shutdown SickRage and remove the `cache.db` file.
- If you use a QNAP and have SSL errors try this [package](http://apps.qnap.community/11-community/17-qsickrage).
- If you have a `'ascii' codec can't encode character` error, than set your Locale to [UTF-8](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#i-have-problems-with-special-characters-%C3%A9-etc-what-can-i-do)

*ps. If you enjoy Sickrage and like the support provided, than please consider making a [donation](https://github.com/SiCKRAGETV/SickRage/wiki/Donations) to keep SickRage alive.*

**Comment by LanMan04** [comment]
I got bit by the exact same thing yesterday.  I updated today (Nov 2 2015) and it *seems* to be resolved.

**Comment by miigotu** [comment]
Not sure where to even look for this one, seems it may have been already fixed =P

**Comment by Peanut-Afl** [comment]
Hi,

I updated tonight to BRANCH: (master) / COMMIT:
(57b043be95f462fa39296de970e0070d6307455d, but the error still occurs.

It happens when I add a show that I already have on disk, in this case Deep
Space 9. It seems to get to S04E02 and then stops. The error then appears.

The following also appears in the log file:

AA
AAAttributeError: 'NoneType' object has no attribute 'replace'
AA    sanitizedDescription = sanitizedDescription.replace(u"\u201c",
"\"").replace(u"\u201d", "\"")
AA  File "C:\SickRage\sickbeard\metadata\tivo.py", line 233, in _ep_data
AA    data = self._ep_data(ep_obj)
AA  File "C:\SickRage\sickbeard\metadata\tivo.py", line 307, in write_ep_file
AA    return self.write_ep_file(ep_obj)
AA  File "C:\SickRage\sickbeard\metadata\generic.py", line 275, in
create_episode_metadata
AA    result = cur_provider.create_episode_metadata(self) or result
AA  File "C:\SickRage\sickbeard\tv.py", line 1849, in createNFO
AA    self.createNFO()
AA  File "C:\SickRage\sickbeard\tv.py", line 1838, in createMetaFiles
AA    rootEp.createMetaFiles()
AA  File "C:\SickRage\sickbeard\tv.py", line 758, in makeEpFromFile
AA    curEpisode = self.makeEpFromFile(ek(os.path.join,
self._location, mediaFile))
AA  File "C:\SickRage\sickbeard\tv.py", line 423, in loadEpisodesFromDir
AA    self.show.loadEpisodesFromDir()
AA  File "C:\SickRage\sickbeard\show_queue.py", line 433, in run
AAAttributeError: 'NoneType' object has no attribute 'replace'
AA    sanitizedDescription = sanitizedDescription.replace(u"\u201c",
"\"").replace(u"\u201d", "\"")
AA  File "C:\SickRage\sickbeard\metadata\tivo.py", line 233, in _ep_data
AA    data = self._ep_data(ep_obj)
AA  File "C:\SickRage\sickbeard\metadata\tivo.py", line 307, in write_ep_file
AA    return self.write_ep_file(ep_obj)
AA  File "C:\SickRage\sickbeard\metadata\generic.py", line 275, in
create_episode_metadata
AA    result = cur_provider.create_episode_metadata(self) or result
AA  File "C:\SickRage\sickbeard\tv.py", line 1849, in createNFO
AA    self.createNFO()
AA  File "C:\SickRage\sickbeard\tv.py", line 1838, in createMetaFiles
AA    rootEp.createMetaFiles()
AA  File "C:\SickRage\sickbeard\tv.py", line 758, in makeEpFromFile
AA    curEpisode = self.makeEpFromFile(ek(os.path.join,
self._location, mediaFile))
AA  File "C:\SickRage\sickbeard\tv.py", line 423, in loadEpisodesFromDir
AA    self.show.loadEpisodesFromDir()
AA  File "C:\SickRage\sickbeard\show_queue.py", line 433, in run
AATraceback (most recent call last):
2015-11-03 23:56:41 ERROR    SHOWQUEUE-ADD :: Error searching dir for
episodes: 'NoneType' object has no attribute 'replace'
2015-11-03 23:56:26 INFO     SHOWQUEUE-ADD :: Building internal name
cache for all shows
2015-11-03 23:56:13 INFO     SHOWQUEUE-ADD :: Setting all episodes to
the specified default status: 5
2015-11-03 23:56:12 INFO     SHOWQUEUE-ADD :: 72073: Unable to find
the show in the database
2015-11-03 23:56:12 INFO     SHOWQUEUE-ADD :: theTVDB: {'useZip':
True, 'apikey': 'F9C450E78D99172E', 'cache':
'C:\\SickRage\\cache\\indexers\\theTVDB', 'language': 'en'}
2015-11-03 23:56:12 INFO     SHOWQUEUE-ADD :: Starting to add show
H:\Series\Star Trek Deep Space 9

Is there anything else you require?

Regards
Peanut

**Comment by miigotu** [comment]
@LanMan04 @Peanut-Afl both are using tivo metadata?

**Comment by LanMan04** [comment]
Nope, WDTV metadata.

**Comment by miigotu** [comment]
@LanMan04 there isnt a single replace call in WDTV metadata provider or it's base class. Do you have the exception from your log FILE?

**Comment by LanMan04** [comment]
Sorry, it already rolled off the end of my logs.   It seemed to be causing
post-processing (but not downloading) to fail, whatever it was.

But like I said, it's now resolved for me.

**Comment by miigotu** [comment]
@Peanut-Afl check the nfo/xml for S04E02. Check the permissions and contents. I have no idea how this can happen from looking at the code.

Also, need that log with exception with debug enabled...

**Comment by Peanut-Afl** [comment]
The S04E02 is actually S04E01E02. I removed this file and one other one (S07E25E26). Once I removed and re-added the series into Sickrage, the error no longer occurred. So I would say that there was something funky with those files.

If you wish, I can re-create the error again as I have a copy of the files, so I can get the debug files for you, otherwise, the issue can now be closed.
