### ISSUE TITLE
Develop branch broken for non-english users with ascii files/shows/episodes

### ISSUE THREAD

**Issue by fernandog** [SiCKRAGETV/sickrage-issues#3587]
HEAD is now at 005bd6e Merge pull request #3113 from labrys/pep8-deluge_client

```
Error !

UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 1: ordinal not in range(128)

<tr class="${show_div}"> <td align="center" nowrap="nowrap"> <% airDate = sbdatetime.sbdatetime.convert_to_setting(cur_result['localtime']) %> <time datetime="${airDate.isoformat('T')}" class="date">${sbdatetime.sbdatetime.sbfdatetime(airDate)}</time> </td> <td align="center" nowrap="nowrap"> <% ends = sbdatetime.sbdatetime.convert_to_setting(cur_ep_enddate) %> <time datetime="${ends.isoformat('T')}" class="date">${sbdatetime.sbdatetime.sbfdatetime(ends)}</time>
/home/osmc/SickRage-test/sickbeard/sbdatetime.py, line 249:
strd += u', ' + dt.strftime(sickbeard.TIME_PRESET)
/home/osmc/SickRage-test/gui/slick/views/schedule.mako, line 122:
<time datetime="${airDate.isoformat('T')}" class="date">${sbdatetime.sbdatetime.sbfdatetime(airDate)}</time>
/home/osmc/SickRage-test/gui/slick/views/layouts/main.mako, line 278:
/home/osmc/SickRage-test/lib/mako/runtime.py, line 883:
callable_(context, *args, **kwargs)
```

**Comment by SiCKRAGEB0T** [comment]
## Thanks for the bug/issue report
Please make sure to submit all of the [required information](https://github.com/SiCKRAGETV/sickrage-issues/blob/master/README.md), or we won't be able to help you!
Provide as **much** information as you can such as debug logs, commit hash, and tell us how to replicate the problem.For basic **questions** use the [ [forum] ](https://sickrage.tv/forums/), and for **Feature Requests** [ [Feathub] ](http://feathub.com/SiCKRAGETV/SickRage)
Also make sure the title accurately describes your issue. ("SR not working" etc. is not ok!)

- [ ] Include basic information: Branch/Commit, OS, What you did, What happened, What you expected
- [ ] Enable debug logging (be sure to disable after the bug is fixed)
- [ ] Post debug logs, either inline (for smaller logs) or using gist)

## Many issues can simply be solved by:
- Making sure you update to the latest version.
- Have you tried turning your device off and on again?
- Using the **search** function to see if this issue has already been reported/solved.
- Do a [GIT reset](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#update-problems-try-this).
- Checking the [ [Wiki] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki) for [ [Guides] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Installation-&-Configuration-Guides), [ [FAQS] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes) [ [Main settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Settings-explained), [ [Show settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Show-settings-explained) [ [Remaining settings] ](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Remaining-settings-explained)
- Shutting down SickRage and removing the `cache/mako` & `cache/sessions` folders.
- If SickRage doesnt find any episodes you probably need to :
 - add a [Scene Exception](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Scene-exceptions-and-numbering)
 - Set the [Default Episode Status](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#newly-aired-shows-are-not-downloading-and-set-to-skippedignored) to `WANTED`
 - Make sure you understand how [quality detection](https://github.com/SiCKRAGETV/sickrage-issues/wiki/Quality-Settings#quality-detectiondetermination) works during searches.
 - Shutdown SickRage and remove the `cache.db` file.
- If you use a QNAP and have SSL errors try this [package](http://apps.qnap.community/11-community/17-qsickrage).
- If you have a `'ascii' codec can't encode character` error, than set your Locale to [UTF-8](https://github.com/SiCKRAGETV/sickrage-issues/wiki/FAQ%27s-and-Fixes#i-have-problems-with-special-characters-%C3%A9-etc-what-can-i-do)

*ps. If you enjoy Sickrage and like the support provided, than please consider making a [donation](https://github.com/SiCKRAGETV/SickRage/wiki/Donations) to keep SickRage alive.*

**Comment by fernandog** [comment]
@neoatomic getting this too?

**Comment by fernandog** [comment]
Also show page is broken:

![image](https://cloud.githubusercontent.com/assets/2620870/11016859/771d09cc-8574-11e5-800b-795f94348259.png)

**Comment by fernandog** [comment]
```
Error !

UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 1: ordinal not in range(128)

<% curStatus, curQuality = Quality.splitCompositeStatus(int(hItem["action"])) %> <tr> <td align="center"> <% airDate = sbdatetime.sbdatetime.sbfdatetime(datetime.datetime.strptime(str(hItem["date"]), History.date_format), show_seconds=True) %> <% isoDate = datetime.datetime.strptime(str(hItem["date"]), History.date_format).isoformat('T') %> <time datetime="${isoDate}" class="date">${airDate}</time> </td> <td class="tvShow" width="35%"><a href="${srRoot}/home/displayShow?show=${hItem["show_id"]}#S${hItem["season"]}E${hItem["episode"]}">${hItem["show_name"]} - ${"S%02i" % int(hItem["season"])}${"E%02i" % int(hItem["episode"])} ${('', '<span class="quality Proper">Proper</span>')["proper" in hItem["resource"].lower() or "repack" in hItem["resource"].lower()]}</a></td> <td align="center" ${('', 'class="subtitles_column"')[curStatus == SUBTITLED]}>
/home/osmc/SickRage-test/sickbeard/sbdatetime.py, line 247:
strd += u', ' + dt.strftime(sickbeard.TIME_PRESET_W_SECONDS)
/home/osmc/SickRage-test/gui/slick/views/history.mako, line 76:
<% airDate = sbdatetime.sbdatetime.sbfdatetime(datetime.datetime.strptime(str(hItem["date"]), History.date_format), show_seconds=True) %>
/home/osmc/SickRage-test/gui/slick/views/layouts/main.mako, line 278:
/home/osmc/SickRage-test/lib/mako/runtime.py, line 883:
callable_(context, *args, **kwargs)
```

**Comment by fernandog** [comment]
needs fixing or reverting SB hack

**Comment by fernandog** [comment]
```
Error !

UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 1: ordinal not in range(128)

% if airDate.year >= 1970 or show.network: <% airDate = sbdatetime.sbdatetime.convert_to_setting(network_timezones.parse_date_time(epResult['airdate'], show.airs, show.network)) %> % endif <time datetime="${airDate.isoformat('T')}" class="date">${sbdatetime.sbdatetime.sbfdatetime(airDate)}</time> % else: Never % endif </td> <td>
/home/osmc/SickRage-test/sickbeard/sbdatetime.py, line 249:
strd += u', ' + dt.strftime(sickbeard.TIME_PRESET)
/home/osmc/SickRage-test/gui/slick/views/displayShow.mako, line 487:
<time datetime="${airDate.isoformat('T')}" class="date">${sbdatetime.sbdatetime.sbfdatetime(airDate)}</time>
/home/osmc/SickRage-test/gui/slick/views/layouts/main.mako, line 278:
/home/osmc/SickRage-test/lib/mako/runtime.py, line 883:
callable_(context, *args, **kwargs)
```

**Comment by fernandog** [comment]
```
Error !

UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 11769: ordinal not in range(128)

</div> <br /> <div class="align-left"><pre> ${logLines} </pre> </div> <br /> </%block>
/home/osmc/SickRage-test/gui/slick/views/viewlogs.mako, line 38:
${logLines}
/home/osmc/SickRage-test/gui/slick/views/layouts/main.mako, line 278:
/home/osmc/SickRage-test/lib/mako/runtime.py, line 883:
callable_(context, *args, **kwargs)
```

**Comment by fernandog** [comment]
nothing works lol
SR broken!

**Comment by duramato** [comment]
Yes it also happens for me

**Comment by miigotu** [comment]
patience.

**Comment by miigotu** [comment]
the dt.strftime error should be fixed now I think. Still need a few more fixes

**Comment by miigotu** [comment]
pushbullet, viewlogs and some others should be fixed also.

need to check notifiers, clients, metadata mostly and figure out wtf is going on with home/displayShow (might not be encoding related)

**Comment by neoatomic** [comment]
Got 3 of the blow errors last night. However all 3 are for [oznzb.com] So maybe that provider is blocking etc. Will check that later today.
Overall my log is extremely quiet, i just noted that only the `INFO` entry's are added.?


```
2015-11-09 10:53:16 INFO     SEARCHQUEUE-DAILY-SEARCH :: Beginning daily search for new episodes
2015-11-09 10:54:13 INFO     SEARCHQUEUE-DAILY-SEARCH :: [Usenet-Crawler] :: Found result The.Walking.Dead.S06E05.INTERNAL.720p.HDTV.x264-KILLERS at https://www.usenet-crawler.com/getnzb/628857952db3e0d738bca23ee5932522.nzb&i=233093&r=**********
2015-11-09 10:54:13 INFO     SEARCHQUEUE-DAILY-SEARCH :: [Usenet-Crawler] :: Found result The.Walking.Dead.S06E05.720p.HDTV.x264-FLEET at https://www.usenet-crawler.com/getnzb/f9aff0221985ebab33b49a7e7cc9a882.nzb&i=233093&r=**********
2015-11-09 10:54:13 INFO     SEARCHQUEUE-DAILY-SEARCH :: [Usenet-Crawler] :: Quality of The.Walking.Dead.S06E05.INTERNAL.720p.HDTV.x264-KILLERS is 720p HDTV
2015-11-09 10:54:13 INFO     SEARCHQUEUE-DAILY-SEARCH :: [Usenet-Crawler] :: Quality of The.Walking.Dead.S06E05.720p.HDTV.x264-FLEET is 720p HDTV
2015-11-09 10:54:13 INFO     SEARCHQUEUE-DAILY-SEARCH :: [oznzb.com] :: Found result The.Walking.Dead.S06E05.INTERNAL.720p.HDTV.x264-KILLERS at https://api.oznzb.com/getnzb/38918171af55c8fcf648d3a3a6c57829.nzb&i=71994&r=**********
2015-11-09 10:54:13 INFO     SEARCHQUEUE-DAILY-SEARCH :: [oznzb.com] :: Found result The.Walking.Dead.S06E05.720p.HDTV.x264-FLEET at https://api.oznzb.com/getnzb/3e6e9879cc14979fcc64b56192672cf5.nzb&i=71994&r=**********
2015-11-09 10:54:13 INFO     SEARCHQUEUE-DAILY-SEARCH :: [oznzb.com] :: Quality of The.Walking.Dead.S06E05.INTERNAL.720p.HDTV.x264-KILLERS is 720p HDTV
2015-11-09 10:54:13 INFO     SEARCHQUEUE-DAILY-SEARCH :: [oznzb.com] :: Quality of The.Walking.Dead.S06E05.720p.HDTV.x264-FLEET is 720p HDTV
2015-11-09 10:54:13 INFO     SEARCHQUEUE-DAILY-SEARCH :: Downloading The.Walking.Dead.S06E05.720p.HDTV.x264-FLEET from Usenet-Crawler
2015-11-09 10:54:13 ERROR    SEARCHQUEUE-DAILY-SEARCH :: Unknown result type, unable to download it
None
```

Also i forgot that i had a documentary in the download folder that wasn't downloaded with SR.
It gave me an error, think its better to make that a warning.

```
2015-11-08 11:05:25 INFO     POSTPROCESSER :: PostProcessing Path: /volume1/public/Download
2015-11-08 11:05:25 INFO     POSTPROCESSER :: Processing /volume1/public/Download/BBC.Timeshift.2015.Battle.for.the.Himalayas.The.Fight.to.Film.Everest.720p.HDTV.x264.AAC.MVGroup.org.mkv (None)
2015-11-08 11:06:32 INFO     POSTPROCESSER :: This show isn't in your list, you need to add it to SR before post-processing an episode
2015-11-08 11:06:32 ERROR    POSTPROCESSER :: Processing failed for /volume1/public/Download/BBC.Timeshift.2015.Battle.for.the.Himalayas.The.Fight.to.Film.Everest.720p.HDTV.x264.AAC.MVGroup.org.mkv: 
Traceback (most recent call last):
  File "/volume1/@appstore/sickrage/var/SickRage/sickbeard/processTV.py", line 554, in process_media
    result.result = processor.process()
  File "/volume1/@appstore/sickrage/var/SickRage/sickbeard/postProcessor.py", line 877, in process
    raise EpisodePostProcessingFailedException()
EpisodePostProcessingFailedException
```

**Comment by neoatomic** [comment]
I see that the episodes in the show are working a little better today.
Now i can see the unaired/downloaded and archived. However still missing `Wanted` episodes. 

And missing a few (recently) downloaded episodes that are on my disk but not showing, and some episodes i removed from my disk and should have gone to `archive 720p HDTV` are not showing in the list.

**Comment by fernandog** [comment]
updated my test SR:

Displat Show:
```
Error !

UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 1: ordinal not in range(128)

% if airDate.year >= 1970 or show.network: <% airDate = sbdatetime.sbdatetime.convert_to_setting(network_timezones.parse_date_time(epResult['airdate'], show.airs, show.network)) %> % endif <time datetime="${airDate.isoformat('T')}" class="date">${sbdatetime.sbdatetime.sbfdatetime(airDate)}</time> % else: Never % endif </td> <td>
/home/osmc/SickRage-test/sickbeard/sbdatetime.py, line 250:
strd += u', ' + dt.strftime(sickbeard.TIME_PRESET)
/home/osmc/SickRage-test/gui/slick/views/displayShow.mako, line 486:
<time datetime="${airDate.isoformat('T')}" class="date">${sbdatetime.sbdatetime.sbfdatetime(airDate)}</time>
/home/osmc/SickRage-test/gui/slick/views/layouts/main.mako, line 277:
/home/osmc/SickRage-test/lib/mako/runtime.py, line 883:
callable_(context, *args, **kwargs)
```

History page:
```
Error !

UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 1: ordinal not in range(128)

<% curStatus, curQuality = Quality.splitCompositeStatus(int(hItem["action"])) %> <tr> <td align="center"> <% airDate = sbdatetime.sbdatetime.sbfdatetime(datetime.datetime.strptime(str(hItem["date"]), History.date_format), show_seconds=True) %> <% isoDate = datetime.datetime.strptime(str(hItem["date"]), History.date_format).isoformat('T') %> <time datetime="${isoDate}" class="date">${airDate}</time> </td> <td class="tvShow" width="35%"><a href="${srRoot}/home/displayShow?show=${hItem["show_id"]}#S${hItem["season"]}E${hItem["episode"]}">${hItem["show_name"]} - ${"S%02i" % int(hItem["season"])}${"E%02i" % int(hItem["episode"])} ${('', '<span class="quality Proper">Proper</span>')["proper" in hItem["resource"].lower() or "repack" in hItem["resource"].lower()]}</a></td> <td align="center" ${('', 'class="subtitles_column"')[curStatus == SUBTITLED]}>
/home/osmc/SickRage-test/sickbeard/sbdatetime.py, line 248:
strd += u', ' + dt.strftime(sickbeard.TIME_PRESET_W_SECONDS)
/home/osmc/SickRage-test/gui/slick/views/history.mako, line 76:
<% airDate = sbdatetime.sbdatetime.sbfdatetime(datetime.datetime.strptime(str(hItem["date"]), History.date_format), show_seconds=True) %>
/home/osmc/SickRage-test/gui/slick/views/layouts/main.mako, line 277:
/home/osmc/SickRage-test/lib/mako/runtime.py, line 883:
callable_(context, *args, **kwargs)
```

Schedule
```
Error !

UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 1: ordinal not in range(128)

<tr class="${show_div}"> <td align="center" nowrap="nowrap"> <% airDate = sbdatetime.sbdatetime.convert_to_setting(cur_result['localtime']) %> <time datetime="${airDate.isoformat('T')}" class="date">${sbdatetime.sbdatetime.sbfdatetime(airDate)}</time> </td> <td align="center" nowrap="nowrap"> <% ends = sbdatetime.sbdatetime.convert_to_setting(cur_ep_enddate) %> <time datetime="${ends.isoformat('T')}" class="date">${sbdatetime.sbdatetime.sbfdatetime(ends)}</time>
/home/osmc/SickRage-test/sickbeard/sbdatetime.py, line 250:
strd += u', ' + dt.strftime(sickbeard.TIME_PRESET)
/home/osmc/SickRage-test/gui/slick/views/schedule.mako, line 122:
<time datetime="${airDate.isoformat('T')}" class="date">${sbdatetime.sbdatetime.sbfdatetime(airDate)}</time>
/home/osmc/SickRage-test/gui/slick/views/layouts/main.mako, line 277:
/home/osmc/SickRage-test/lib/mako/runtime.py, line 883:
callable_(context, *args, **kwargs)
```

**Comment by duramato** [comment]
History page ,and shoes list is now working

**Comment by fernandog** [comment]
some displayShow works, most shows don't work 
history not working for me.

**Comment by duramato** [comment]
actually 
```
2015-11-09 14:20:35 DEBUG    TORNADO :: Failed doing webui request "update": Traceback (most recent call last):
AAUnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 318: ordinal not in range(128)
AA    logger.log(u"Pushbullet response: %r" % response.text, logger.DEBUG)
AA  File "/home/home/SickRage/sickbeard/notifiers/pushbullet.py", line 106, in _sendPushbullet
AA    if sickbeard.PUSHBULLET_NOTIFY_ONDOWNLOAD:
AA  File "/home/home/SickRage/sickbeard/notifiers/pushbullet.py", line 55, in notify_git_update
AA    n.notify_git_update(new_version)
AA  File "/home/home/SickRage/sickbeard/notifiers/__init__.py", line 112, in notify_git_update
AA    notifiers.notify_git_update(sickbeard.CUR_COMMIT_HASH if sickbeard.CUR_COMMIT_HASH else "")
AA  File "/home/home/SickRage/sickbeard/versionChecker.py", line 641, in update
AA    return self.updater.update()
AA  File "/home/home/SickRage/sickbeard/versionChecker.py", line 330, in update
AA    if sickbeard.versionCheckScheduler.action.update():
AA  File "/home/home/SickRage/sickbeard/webserve.py", line 1116, in update
AA    result = function(**kwargs)
AA  File "/home/home/SickRage/sickbeard/webserve.py", line 261, in async_call
AATraceback (most recent call last):
AAUnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 318: ordinal not in range(128)
AA    logger.log(u"Pushbullet response: %r" % response.text, logger.DEBUG)
AA  File "/home/home/SickRage/sickbeard/notifiers/pushbullet.py", line 106, in _sendPushbullet
AA    if sickbeard.PUSHBULLET_NOTIFY_ONDOWNLOAD:
AA  File "/home/home/SickRage/sickbeard/notifiers/pushbullet.py", line 55, in notify_git_update
AA    n.notify_git_update(new_version)
AA  File "/home/home/SickRage/sickbeard/notifiers/__init__.py", line 112, in notify_git_update
AA    notifiers.notify_git_update(sickbeard.CUR_COMMIT_HASH if sickbeard.CUR_COMMIT_HASH else "")
AA  File "/home/home/SickRage/sickbeard/versionChecker.py", line 641, in update
AA    return self.updater.update()
AA  File "/home/home/SickRage/sickbeard/versionChecker.py", line 330, in update
AA    if sickbeard.versionCheckScheduler.action.update():
AA  File "/home/home/SickRage/sickbeard/webserve.py", line 1116, in update
AA    result = function(**kwargs)
AA  File "/home/home/SickRage/sickbeard/webserve.py", line 261, in async_call
2015-11-09 14:20:35 ERROR    Thread-49 :: Failed doing webui callback: Traceback (most recent call last):
 ```

**Comment by duramato** [comment]
log
```
Error !

UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 4920: ordinal not in range(128)

</div> <br> <div class="align-left"><pre> ${logLines} </pre> </div> <br> </%block>
/home/home/SickRage/gui/slick/views/viewlogs.mako, line 38:
${logLines}
/home/home/SickRage/gui/slick/views/layouts/main.mako, line 277:
/home/home/SickRage/lib/mako/runtime.py, line 883:
callable_(context, *args, **kwargs)
```

**Comment by neoatomic** [comment]
The post processing with nzbtomedia isn't working for me anymore. (was working yesterday)
I use NZBGet that has the scripts build-in, and noting has changed there.

Looking trough the log i see those two lines. : 

```
[13:44:59] [INFO]::MAIN: SickBeard:tv fork auto-detection found custom params {'failed': None, 'force': None, 'process_method': None}
[13:44:59] [INFO]::MAIN: SickBeard:tv fork set to custom
```

Log : http://pastebin.com/raw.php?i=Awp8eZmf

Those should be : 

```
[13:11:29] [INFO]::MAIN: SickBeard:tv fork auto-detection successful ...
[13:11:29] [INFO]::MAIN: SickBeard:tv fork set to sickrage
```
SickRage isn't detected anymore, this is probably API related.?

**Comment by miigotu** [comment]
@neoatomic found the webapi problems I think. As for missing episodes in displayShow you need to clear your browser cache or ctrl+f5 (it was broken js causing that one)

**Comment by fernandog** [comment]
all errors have "0xc3". that's odd

**Comment by neoatomic** [comment]
@miigotu The episodes are fixed now and showing correctly.

@fernandog Did note that already yesterday. Seems that its a `Ă` character.

`My guess is that your input is encoded as ISO-8859-2 which contains Ă as 0xC3. Check the encoding of your input file.`

**Comment by fernandog** [comment]
@neoatomic sorry, didn't understand.

**Comment by neoatomic** [comment]
@fernandog Thats just a quote from another project that had the `can't decode 0xC3 error`. :P

**Comment by duramato** [comment]
I think doesnt matter it is the sane for me and I don't have any `Ă`

**Comment by miigotu** [comment]
https://bugs.python.org/issue5398

**Comment by fernandog** [comment]
no official issue for that since 2009?!

**Comment by miigotu** [comment]
Just need to decode it manually before calling str() on it or concatenating it to a unicode string. Fixed in github.com/SiCKRAGETV/SickRage/#3161

**Comment by fernandog** [comment]
@miigotu last update fixed schedule/home/display. thanks

**Comment by fernandog** [comment]
this hasnt changed: servi\\xc3\\xa7o

Connection error to getURL http://sickragetv.github.io/sb_tvdb_scene_exceptions/exceptions.txt Error: u"error ('Connection aborted.', gaierror(-2, 'Nome ou servi\\xc3\\xa7o desconhecido'))"

**Comment by miigotu** [comment]
because it is repr.....

**Comment by miigotu** [comment]
@fernandog The problem is that one of the arguments is another exception, ex does not handle this and just returns the string prepresentation of the error class. maybe try just:
logger.log(u"Connection error to getURL %s Error: %s" % (url, string(e).encode(sickbeard.SYS_ENCODING)), logger.WARNING)

**Comment by fernandog** [comment]
will try. thanks

**Comment by fernandog** [comment]
```
2015-11-10 07:59:18 Thread-19 :: Failed doing webui callback: Traceback (most recent call last):
  File "/home/osmc/SickRage-test/sickbeard/webserve.py", line 261, in async_call
    result = function(**kwargs)
  File "/home/osmc/SickRage-test/sickbeard/webserve.py", line 501, in schedule
    t = PageTemplate(rh=self, filename='schedule.mako')
  File "/home/osmc/SickRage-test/sickbeard/webserve.py", line 112, in __init__
    self.template = lookup.get_template(filename)
  File "/home/osmc/SickRage-test/lib/mako/lookup.py", line 256, in get_template
    return self._load(srcfile, uri)
  File "/home/osmc/SickRage-test/lib/mako/lookup.py", line 321, in _load
    **self.template_args)
  File "/home/osmc/SickRage-test/lib/mako/template.py", line 322, in __init__
    module = self._compile_from_file(path, filename)
  File "/home/osmc/SickRage-test/lib/mako/template.py", line 378, in _compile_from_file
    self.module_writer)
  File "/home/osmc/SickRage-test/lib/mako/template.py", line 692, in _compile_module_file
    generate_magic_comment=True)
  File "/home/osmc/SickRage-test/lib/mako/template.py", line 657, in _compile
    node = lexer.parse()
  File "/home/osmc/SickRage-test/lib/mako/lexer.py", line 237, in parse
    if self.match_control_line():
  File "/home/osmc/SickRage-test/lib/mako/lexer.py", line 429, in match_control_line
    self.append_node(parsetree.ControlLine, keyword, isend, text)
  File "/home/osmc/SickRage-test/lib/mako/lexer.py", line 134, in append_node
    node = nodecls(*args, **kwargs)
  File "/home/osmc/SickRage-test/lib/mako/parsetree.py", line 83, in __init__
    code = ast.PythonFragment(text, **self.exception_kwargs)
  File "/home/osmc/SickRage-test/lib/mako/ast.py", line 105, in __init__
    super(PythonFragment, self).__init__(code, **exception_kwargs)
  File "/home/osmc/SickRage-test/lib/mako/ast.py", line 40, in __init__
    expr = pyparser.parse(code.lstrip(), "exec", **exception_kwargs)
  File "/home/osmc/SickRage-test/lib/mako/pyparser.py", line 48, in parse
    ), **exception_kwargs)
SyntaxException: (SyntaxError) EOL while scanning string literal (, line 1) (u"if sickbeard.COMING_EPS_SORT == 'network:pass") in file '/home/osmc/SickRage-test/gui/slick/views/schedule.mako' at line: 216 char: 1

```

**Comment by OmgImAlexis** [comment]
@fernandog the whole thing shouldn't be unicode? That makes no sense. Shouldn't just the strings be set?

Also there's a missing single quote after `network:pass`.

**Comment by fernandog** [comment]
@OmgImAlexis 

https://github.com/SiCKRAGETV/SickRage/commit/e8c5912099a266dd7006a3ed65ed4678c58d5b2e

**Comment by OmgImAlexis** [comment]
Ah, that was just the console output that showed the whole `(u"if sickbeard.COMING_EPS_SORT == 'network:pass")` I figured the `(u"` was part of the code.

**Comment by fernandog** [comment]
tested and no issues in dailysearch with special chars:
`Unable to parse the filename 육룡이.나르샤.E11.151109.720p.HDTV.x264-RAiN.mkv into a valid show`

**Comment by miigotu** [comment]
PP is broken, working on it. os.walk causes issues with unicode so I might need to write my own..

**Comment by jrgprzm** [comment]
This is the same issue as #3554 I think. I can't comment in the other thread but the issue is solved by changing:

SickRage-master/sickbeard/postProcessor.py", line 160
    for base, _, files in os.walk(treeroot):
to
    for base, _, files in os.walk(treeroot.encode("utf-8")):

I changed in my local and is now working

**Comment by arkdelkaos** [comment]
commit ad3c9258922fb6ee3761fb3ffcf0a0db668f0e21
Date:   Thu Nov 12 10:56:39 2015 -0800
locale: English AFAIK

````
Error !

UnicodeDecodeError: 'ascii' codec can't decode byte 0xcc in position 34: ordinal not in range(128)

<meta data-var="sickbeard.HOME_LAYOUT" data-content="${sickbeard.HOME_LAYOUT}"> <meta data-var="sickbeard.POSTER_SORTBY" data-content="${sickbeard.POSTER_SORTBY}"> <meta data-var="sickbeard.POSTER_SORTDIR" data-content="${sickbeard.POSTER_SORTDIR}"> <meta data-var="sickbeard.ROOT_DIRS" data-content="${sickbeard.ROOT_DIRS}"> <meta data-var="sickbeard.SORT_ARTICLE" data-content="${sickbeard.SORT_ARTICLE}"> <meta data-var="sickbeard.TIME_PRESET" data-content="${sickbeard.TIME_PRESET}"> <meta data-var="sickbeard.TRIM_ZERO" data-content="${sickbeard.TRIM_ZERO}"> <%block name="metas" />
/Users/ark/SickRage/gui/slick/views/layouts/main.mako, line 59:
<meta data-var="sickbeard.ROOT_DIRS" data-content="${sickbeard.ROOT_DIRS}">
/Users/ark/SickRage/lib/mako/runtime.py, line 883:
callable_(context, *args, **kwargs)
````
