### ISSUE TITLE
Iptorrents invalid username or password

### ISSUE THREAD

**Issue by Jezze83** [SiCKRAGETV/sickrage-issues#523]
I just logged in to iptorrent website with my username and password. I checked from sickrage config.ini file, there is same username and password. Sickrage give me errors with master and develop. Can someone fix this as soon as possible? That worked fine couple days ago.

```
2015-01-31 01:25:42 INFO     SEARCHQUEUE-MANUAL-22622 :: Unable to find a download for: [Modern Family - 6x09 - Strangers in the Night]
2015-01-31 01:25:42 ERROR    SEARCHQUEUE-MANUAL-22622 :: Invalid username or password for IPTorrents, Check your settings!
2015-01-31 01:25:42 INFO     SEARCHQUEUE-MANUAL-22622 :: Performing season pack search for Modern Family
2015-01-31 01:25:42 INFO     SEARCHQUEUE-MANUAL-22622 :: FALLBACK SEASON PACK SEARCH INITIATED ...
AANone
2015-01-31 01:25:42 ERROR    SEARCHQUEUE-MANUAL-22622 :: [IPTorrents] :: Invalid username or password for IPTorrents, Check your settings!
2015-01-31 01:25:41 INFO     SEARCHQUEUE-MANUAL-22622 :: [IPTorrents] :: Performing episode search for Modern Family
2015-01-31 01:25:41 INFO     SEARCHQUEUE-MANUAL-22622 :: Building internal name cache for Modern Family
```

**Comment by abeloin** [comment]
Try removing the www from www.iptorrents.eu in sickbeard/providers/iptorrents.py and restart sickrage.

Reference commit https://github.com/coolius/SickRage/commit/bef446186ee234303f9c3bbe449abe7696c7659b

**Comment by acecon** [comment]
I had the same problem, but instead of removing www, I changed .eu to .com. It's working again. I'm in the US.

**Comment by fernandog** [comment]
Please use the issue guidelines when posting an issue. This way the dev team is able to debug your problem. Don't forget to use [markdown](https://guides.github.com/features/mastering-markdown/) on any code and log you want to post in-line.

- [ ] Branch
- [ ] Commit hash
- [ ] Operating system and python version
- [ ] What did you do?
- [x] What happened?
- [x] What did you expect?
- [ ] Link to a copy/paste of your logfile with clear debug info of the error on [pastebin](http://pastebin.com/) (or in-line using [markdown](https://guides.github.com/features/mastering-markdown/) for small snippets)

**Comment by Jezze83** [comment]
I dont understand that what happened and what did u expect. I already told what happened, worked couple days ago and suddenly didnt worked anymore. But that what what did u expect, what it means? What should i expect? Ill try soon that what @acecon said.

**Comment by Jezze83** [comment]
Now it works, that would be nice if its updated to develop version. Thanks @abeloin and @acecon

**Comment by abeloin** [comment]
@fernandog Fixed with pull request SiCKRAGETV/SickRage#1267

**Comment by fernandog** [comment]
Thanks!

**Comment by MLWALK3R** [comment]
I just tested this that pull request SiCKRAGETV/SickRage#1267 and it doesn't fix it for me.

```bash
2015-02-01 12:04:53 FINDPROPERS :: [IPTorrents] :: Invalid username or password for IPTorrents, Check your settings!
2015-02-01 12:04:53 FINDPROPERS :: [IPTorrents] :: Invalid username or password for IPTorrents, Check your settings!
2015-02-01 12:04:53 FINDPROPERS :: [IPTorrents] :: Invalid username or password for IPTorrents, Check your settings!
2015-02-01 12:04:53 FINDPROPERS :: [IPTorrents] :: Invalid username or password for IPTorrents, Check your settings!
```

**Comment by fernandog** [comment]
@Jezze83  develop updated. please test and report back

**Comment by MLWALK3R** [comment]
Just test the latest dev branch and it has no errors for IPT.
