### ISSUE TITLE
restarting after update launches new process

### ISSUE THREAD

**Issue by dgholz** [SiCKRAGETV/sickrage-issues#794]
Hi, I'm writing a docker to run SickRage as pid 1, so when it updates and starts the new process, docker thinks SickRage is finished and shuts down the container.

The docker image is published in the public docker registry as dgholz/sickrage and is build from https://github.com/dgholz/sickrage/blob/master/Dockerfile

**Comment by fernandog** [comment]
@dgholz what about this?

https://github.com/SiCKRAGETV/SickRage/pull/1590

Is it a fix?  isn't better than change that 36 files?

**Comment by TagForce** [comment]
https://github.com/docker/docker/pull/7414
together with our option to shutdown only should fix it.

**Comment by dgholz** [comment]
@fernandog #1590 is close but not the same, docker sees the original process has terminated and thus stops the container. I'm fine running docker with a restart policy, but now I have to explain restart policies in the documentation for the docker image. I will advise users not to attempt to upgrade SickRage within a docker container.

**Comment by dgholz** [comment]
To be clear, #1590 doesn't fix this issue. An alternate fix would be an option to disable updating and to remove the 'you are XXX commits behind master' banner.

**Comment by dgholz** [comment]
@fernandog 30 of the 31 changed files are just variable renames, I can resubmit with just the functional changes if you prefer.

**Comment by fernandog** [comment]
Why #1590 does not fix?

Why disable the banner and why not update? 
We wont support outdated versions.
We recommend auto-update.

**Comment by abeloin** [comment]
@dgholz Maybe using supervisor [supervisord](http://supervisord.org/) would resolve this issue?

**Comment by ArchiFleKs** [comment]
Supervisord does not solve the issue, you have a two cases scenario:

- Autorestart with supervisord : when updated, sickrage shutdown but not the docker container so sickrage restart itself  with the updated version and supervisord restart sickrage too so you have two instances running at the same time.

- Autorestart disable with supervisord : when updated, sickrage shutdown but not the docker container so sickrage restart itself with the updated version but not supervisord so it is working fine but sickrage is no longer manage by supervisord. 

I'm using the second option for now but I think an option to shutdown sickrage and not restart it after upgrade would be OK zhen running in docker.

Even with the docker option --restart, the container would still restart with an outdated version of sickrage if the image as not been updated,
