### ISSUE TITLE
REQUEST/SUGESTION 'no items found in the RSS feed' - use your proxies 

### ISSUE THREAD

**Issue by vanticar** [SiCKRAGETV/sickrage-issues#848]
I would like an option to use your coded sickrage proxy sites under provider options in the Add Custom Torrent Provider because when i try and add new sites I get the 'no items found in the RSS feed' error.
I then cannot save to enable this check via a proxy or perhaps an option to save it regardless then to go into the provider options tab and enable the via proxy option and see if any errors i get in the logs?

thanks

**Comment by fernandog** [comment]
@abeloin 

can we do this?

https://github.com/SiCKRAGETV/SickRage/blob/develop/sickbeard/providers/rsstorrent.py#L164
```
    def _getRSSData(self):
        logger.log(u"TorrentRssCache cache update URL: " + self.provider.url, logger.DEBUG)

        if self.provider.cookies:
            self.provider.headers.update({'Cookie': self.provider.cookies})

        if sickbeard.PROXY_SETTING:
            logger.log("Using proxy for url: " + self.provider.url, logger.DEBUG)
            session.proxies = {
                "http": sickbeard.PROXY_SETTING,
                "https": sickbeard.PROXY_SETTING,
            }
```

**Comment by abeloin** [comment]
PR https://github.com/SiCKRAGETV/SickRage/pull/1502 can be used as a workaround for now.

**Comment by fernandog** [comment]
@vanticar please update and report back (develop branch)

**Comment by vanticar** [comment]
@fernandog I dont understand what do you need me to do? also please allow for TZ differeneces - I am GMT not EST, thankyou

**Comment by fernandog** [comment]
You asked "I would like an option to use your coded sickrage proxy sites under provider options in the Add Custom Torrent Provide" and we did. We want you to test !

**Comment by vanticar** [comment]
oh ok sorry i am not sure what i am supposed to do? - if i try and ad say http://extratorrent.cc or http://extratorrent.cc/rss.xml i get the no feed error currently - but presumably i have to update some files? unsure what git commands to use (old ftp user here) - do you have an ftp server for me to download files or was it updated in last updates in sickrage?

**Comment by fernandog** [comment]
no. are you using the lastest update? If so, don't need to change any files

extratorrent used to get error and now it don't? So is fixed, isn't?

**Comment by vanticar** [comment]
@fernandog I still get error when trying to add  http://extratorrent.cc or http://extratorrent.cc/rss.xml

**Comment by vanticar** [comment]
I still get error when trying to add http://extratorrent.cc or 
http://extratorrent.cc/rss.xml

------ Original Message ------

**Comment by fernandog** [comment]
@vanticar did you enabled global proxy in Advanced settings ?

**Comment by vanticar** [comment]
/config/general/ - Adavnced Use proxy for indexers - use proxy host for connecting to indexers (thetvdb, tvrage) - TICKED

still same error 'no items found in RSS feed' using  http://extratorrent.cc or http://extratorrent.cc/rss.xml

no change - sorry

**Comment by vanticar** [comment]
FYI http://extratorrent.cc/category/8/TV+Torrents.html is the pages / feeds i am trying to use

**Comment by fernandog** [comment]
@vanticar what's the content of "Proxy host" in Advanced Settings?

**Comment by fernandog** [comment]
@abeloin 
is this a proper XML feed - http://extratorrent.cc/rss.xml?cid=8&type=last ? 
I don't think so

**Comment by vanticar** [comment]
@fernandog Proxy host - 'BLANK'

FYI (i was also trying to add rarbg https://rarbg.com/rssdd.php but this has now been added with a different feed?) - my other github errors (are these related?) for this is https://github.com/SiCKRAGETV/sickrage-issues/issues/849#issuecomment-77839160

**Comment by fernandog** [comment]
@vanticar rarbg is in the provider list! are you using that? why add a rarbg as rss if we have in the provider list?

**Comment by vanticar** [comment]
lol - it wasnt until recently. My original post / sugestion on the sickrage forum was to add that feed before it was included in the last update (extratorrent was not however) because https://rarbg.com/rssdd.php  also did not work - it was more FYI with the errors i am having with rarbg and the code i have now tried uses a different feed(s) https://rarbg.com',

                     'base_url': 'https://rarbg.com/torrents.php',
                     'search': 'https://rarbg.com/torrents.php?search=%s&category=%s&page=%s',
                     'download': 'https://rarbg.com/download.php?id=%s&f=%s',

rather than the one i was using the official RSS feed (before latest update)

 'https://rarbg.com/rssdd.php'

which also does not work
